-- MySQL Script generated by MySQL Workbench
-- Thu 29 Sep 2022 10:02:26 PM EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema the_concept_academy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema the_concept_academy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `the_concept_academy` ;
USE `the_concept_academy` ;

-- -----------------------------------------------------
-- Table `the_concept_academy`.`coupons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `the_concept_academy`.`coupons` (
  `coupon_id` BIGINT NOT NULL AUTO_INCREMENT,
  `coupon_text` VARCHAR(8) NOT NULL,
  `coupon_value` FLOAT NOT NULL,
  PRIMARY KEY (`coupon_id`));


-- -----------------------------------------------------
-- Table `the_concept_academy`.`lectures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `the_concept_academy`.`lectures` (
  `lecture_id` BIGINT NOT NULL AUTO_INCREMENT,
  `lecture_name_en` VARCHAR(100) NOT NULL,
  `lecture_name_ar` VARCHAR(100) NOT NULL,
  `lecture_desc_en` VARCHAR(2000) NOT NULL,
  `lecture_desc_ar` VARCHAR(2000) NOT NULL,
  `thumbnail` VARCHAR(100) NOT NULL,
  `price` FLOAT NOT NULL,
  `duration` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`lecture_id`));


-- -----------------------------------------------------
-- Table `the_concept_academy`.`announcements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `the_concept_academy`.`announcements` (
  `announcement_id` BIGINT NOT NULL AUTO_INCREMENT,
  `announcement_desc_en` VARCHAR(2000) NOT NULL,
  `announcement_desc_ar` VARCHAR(2000) NOT NULL,
  `announcement_link` VARCHAR(2000) NOT NULL,
  `announcement_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`announcement_id`));


-- -----------------------------------------------------
-- Table `the_concept_academy`.`payment_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `the_concept_academy`.`payment_logs` (
  `payment_log_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `log_datetime` DATETIME NOT NULL,
  `payment_log_text` VARCHAR(4096) NOT NULL,
  PRIMARY KEY (`payment_log_id`));


-- -----------------------------------------------------
-- Table `the_concept_academy`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `the_concept_academy`.`materials` (
  `material_id` INT NOT NULL AUTO_INCREMENT,
  `lecture_id` BIGINT NOT NULL,
  `material_type` VARCHAR(50) NOT NULL,
  `material_order` INT NOT NULL,
  `material_name_en` VARCHAR(100) NOT NULL,
  `material_name_ar` VARCHAR(100) NOT NULL,
  `material_link` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`material_id`),
  INDEX `fk_materials_lectures1_idx` (`lecture_id` ASC) VISIBLE,
  CONSTRAINT `fk_materials_lectures1`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `the_concept_academy`.`lectures` (`lecture_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `the_concept_academy`.`quiz_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `the_concept_academy`.`quiz_answers` (
  `quiz_answer_id` BIGINT NOT NULL AUTO_INCREMENT,
  `material_id` INT NOT NULL,
  `question_order` INT UNSIGNED NOT NULL,
  `answer_char` CHAR NOT NULL,
  PRIMARY KEY (`quiz_answer_id`),
  INDEX `fk_quiz_answers_materials1_idx` (`material_id` ASC) VISIBLE,
  CONSTRAINT `fk_quiz_answers_materials1`
    FOREIGN KEY (`material_id`)
    REFERENCES `the_concept_academy`.`materials` (`material_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `the_concept_academy`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `the_concept_academy`.`users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(50) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `pass_hash` VARCHAR(128) NOT NULL,
  `user_role` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `parent_phone_number` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `balance` FLOAT NOT NULL,
  `reg_type` VARCHAR(100) NOT NULL,
  `grade` INT UNSIGNED NOT NULL,
  `center_name` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `the_concept_academy`.`users_lectures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `the_concept_academy`.`users_lectures` (
  `user_id` BIGINT NOT NULL,
  `lecture_id` BIGINT NOT NULL,
  INDEX `fk_users_lectures_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_users_lectures_lectures1_idx` (`lecture_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_lectures_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `the_concept_academy`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_lectures_lectures1`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `the_concept_academy`.`lectures` (`lecture_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
