-- this sql script clears data generated by the test units

-- clean fake users (not needed)
DELETE FROM users WHERE username LIKE 'test_user_%';

-- clean fake coupons (not needed)
DELETE FROM coupons;

-- note: for test to be valid we need at least one owned lecture